#!/usr/bin/env bash
source ~/.aliases
case "$(uname -s)" in

    Darwin)

    # Ask for the administrator password upfront
    sudo -v

    # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    #press and hold will repeat keys.
    defaults write -g ApplePressAndHoldEnabled -bool false
    
    sudo spctl --master-disable
    

    ;;
    Linux)
    sudo root
    update

    ;;






esac
